version: "2.14"

services:
  web:
    build: ./BraniacLMS
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./BraniacLMS/:/usr/src/BraniacLMS/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: "braniac"
      POSTGRES_USER: "django"
      POSTGRES_PASSWORD: "geekbrains"
    volumes:
      - ./braniac:/var/lib/postgresql/data
